### ISSUE TITLE
`C-n` always applies the first item but `<Down>` works as expected by only previewing the items

### ISSUE THREAD

**Issue by kohane27** [milanglacier/minuet-ai.nvim#16]
Hello! Hope you're doing well. Thank you for creating this awesome plugin! It makes integration LLM into Neovim much smoother!

I  found the following bug:

https://github.com/user-attachments/assets/e5912738-a422-45c5-8348-3d376785424c

- Pressing `C-n` will *almost* always apply the first item. I can't preview the second or third one because the first one gets applied automatically.
- Not the whole suggestion is applied; only the first line is applied.
- Pressing `<Down>` does not have this bug: I can preview other suggestions.
- I tried using Claude and Gemini and they both have this bug.

For suggestions like comments, pressing `C-n`, more often than not, does not result in this bug, i.e., I can press `C-n` to preview the suggestions:

https://github.com/user-attachments/assets/3799abef-c34c-443c-bddc-cc9933be11f2

It seems like, this bug is triggered if the first suggestion is multi-line?

Testing code snippet:

```js
async function fetchData() {
  try {
    const response = await fetch('https://api.example.com/data');
    const data = await response.json();
    return data;
  } catch (error) {
    console.error(error);
  }
}
```

Triggering minuet-ai.nvim under `response` always resulting in this "auto-apply" bug.

Minimal `nvim-cmp`:

```lua
return {
  "hrsh7th/nvim-cmp",
  lazy = false,
  dependencies = { "hrsh7th/cmp-nvim-lsp", },
  config = function()
    local cmp = require("cmp")

    cmp.setup({
      mapping = cmp.mapping.preset.insert({
        ["<C-e>"] = require("minuet").make_cmp_map(),
        ["<CR>"] = cmp.mapping.confirm({ select = true }),
      }),
      performance = {
        -- slower response speed of LLMs
        fetching_timeout = 2000,
      },
    })
  end,
}
```

Thank you!

**Comment by milanglacier** [comment]
This is a `nvim-cmp` bug. I do also encounter this bug. This issue often occurs when the completion item is a multi-lines text.

If you take a look at part of my nvim-cmp config:

```lua
local mappings = {
                -- Select the candidates in nvim-cmp window and also insert the text into the buffer
                ['<C-n>'] = cmp.mapping.select_next_item { behavior = types.cmp.SelectBehavior.Insert },
                ['<C-p>'] = cmp.mapping.select_prev_item { behavior = types.cmp.SelectBehavior.Insert },
                ['<Down>'] = cmp.mapping.select_next_item { behavior = types.cmp.SelectBehavior.Insert },
                ['<Up>'] = cmp.mapping.select_prev_item { behavior = types.cmp.SelectBehavior.Insert },
                -- Select the candidates in nvim-cmp window but don't insert the text into the buffer
                ['<C-j>'] = cmp.mapping.select_next_item { behavior = types.cmp.SelectBehavior.Select },
                ['<C-k>'] = cmp.mapping.select_prev_item { behavior = types.cmp.SelectBehavior.Select },
}
```

`<C-j>` and `<C-k>` does not have this bug because the completion item will not be inserted into the buffer, you will need to press `<CR>` or `<Tab>` to insert the completion item into the buffer.

I recommend you try `magazine.nvim` which is a more actively maintained fork (which is also what I am using), and see if this bug occurs less frequently.

**Comment by kohane27** [comment]
@milanglacier Thank you for looking into this issue; I appreciate it. Apologies for the noise; I didn't realize it's cmp problem; I tried multiline luasnippets and also found the same problem. Thank you again and have a good day!
