### ISSUE TITLE
Configuration for ollama/qwen2.5-coder

### ISSUE THREAD

**Issue by schuhmc** [milanglacier/minuet-ai.nvim#20]
I'm trying to use qwen2.5-coder locally with ollama and I'm having a hard time getting the setup right.

The connection is working, but the suggestions I get are often quite bad (containing quotes and backticks where they don't make any sense for example) . When I use continue.dev in VSCode with the same server and model, the suggestions are much better. I think it has something to do with the template, but I'm not sure how to fix it.

There should be some useful reference [in the continue templates](https://github.com/continuedev/continue/blob/89344289e7e5c981979eab6876e49c54630ff412/core/autocomplete/templating/AutocompleteTemplate.ts#L48) but it seems like I'm doing something wrong.

This is my current configuration:
```lua
    require("minuet").setup {
        after_cursor_filter_length = 20,
        provider = 'openai_compatible',
        provider_options = {
            openai_compatible = {
                model = "qwen2.5-coder:3b",
                system = {
                    template = '<|fim_prefix|><contextAfterCursor><|fim_suffix|><contextBeforeCursor><|fim_middle|>'
                },
                few_shots = defaults_few_shots,
                end_point = "http://192.168.0.233:11434/v1/chat/completions",
                name = "Ollama",
                stream = true,
                api_key = 'DEEPSEEK_API_KEY',
                optional = {
                    stop = nil,
                    max_tokens = nil,
                }
            }
        }
```
```lua
    local cmp = require('cmp')
    cmp.setup ({
     snippet = {
          -- REQUIRED - you must specify a snippet engine
          expand = function(args)
            vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
          end,
        },
        window = {
          completion = cmp.config.window.bordered(),
          documentation = cmp.config.window.bordered(),
        },
        mapping = cmp.mapping.preset.insert({
          ['<C-b>'] = cmp.mapping.scroll_docs(-4),
          ['<C-f>'] = cmp.mapping.scroll_docs(4),
          ['<C-Space>'] = cmp.mapping.complete(),
          ['<C-e>'] = cmp.mapping.abort(),
          ['<Tab>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          ['C-x'] = require('minuet').make_cmp_map(),
    }),
        sources = {
          { name = 'otter' },
          { name = 'nvim_lsp_signature_help' },
          { name = 'nvim_lsp' },
          { name = 'vsnip' }, -- For vsnip users.
          { name = 'path' },
          { name = 'buffer' },
          { name = 'minuet' },
        },
        performance = {
            fetching_timeout = 2000,
        }
      })
...
```

**Comment by milanglacier** [comment]
Can you try the default template and see if it works?

My understanding is that Qwen2.5 is an intelligent model and you can ask them to perform the task through a chat interface.

I can't run Ollama with Qwen2.5 because my machine cannot run a 32B model. But I tried `Qwen/Qwen2.5-Coder-32B-Instruct` model with `deepinfra` through `openai_compatible` provider using the default template. It works fine.

Beside, if you want to use FIM completion, you will need to use `openai_fim_compatible` provider, not `openai_compatible` provider. But I am not sure if `ollama` support the legacy completion interface.

**Comment by milanglacier** [comment]
Hi sorry for the confusions. I was thinking that you are using a 32b model, but you are actually using the 3b model. My apology.

And ollama does support the openAI legacy completion API. I have not used a FIM model for a long time and forgot it. So I think you can just change your provider from`openai_compatible` to `openai_fim_compatible` and see if it works.

**Comment by schuhmc** [comment]
Thank you very much, I think I got it working now!

I actually tried to use the `openai_fim_compatible` provider already, but I probably had some other issue because I couldn't get it to work.

Anyways, here's my config for ollama qwen2.5-coder in case anyone needs it:

```lua
    require("minuet").setup {
        after_cursor_filter_length = 20,
        provider = 'openai_fim_compatible',
        provider_options = {
            openai_fim_compatible = {
                model = "qwen2.5-coder:3b",
                end_point = "http://192.168.0.233:11434/v1/completions",
                name = "Ollama",
                stream = true,
                api_key = 'DEEPSEEK_API_KEY',
                optional = {
                    stop = nil,
                    max_tokens = nil,
                }
            }
        }
```
