### ISSUE TITLE
[Feature request] proxy support for `curl`?

### ISSUE THREAD

**Issue by kohane27** [milanglacier/minuet-ai.nvim#9]
Hello there. Hope you're doing well. Thank you for creating this plugin that supports Claude for completion.

## Description

I'm using [proton-privoxy](https://github.com/walterl/proton-privoxy) to use a proxy to access llm's API.

Currently I use a fork of yours:

```lua
job:new({
    command = 'curl',
    args = {
        'https://api.anthropic.com/v1/messages',
        '-H',
        'Content-Type: application/json',
        '-H',
        'x-api-key: ' .. vim.env.ANTHROPIC_API_KEY,
        '-H',
        'anthropic-version: 2023-06-01',
        '--proxy',
        'http://127.0.0.1:8888',
        '--max-time',
        tostring(config.request_timeout),
        '-d',
        '@' .. data_file,
    }
    })
```

Adding `'--proxy', 'http://127.0.0.1:8888'` is enough to make it work. But I'm not sure how to best integrate into the codebase. Thank you again!

**Comment by milanglacier** [comment]
Thanks for the update. I can add an option proxy in the setup function.

**Comment by kohane27** [comment]
Thank you for indulging my request.

I can confirm that the following works:

```lua
return {
  "milanglacier/minuet-ai.nvim",
  branch = "feature/proxy",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "hrsh7th/nvim-cmp",
  },
  opts = {
    provider = "claude",
    proxy = "http://127.0.0.1:8888",
  },
}
```

Thank you again!
